### PR TITLE
Add support for SQLite

### PR DESCRIPTION
**Pull request by lokenx**
I was looking to use your plugin but with SQLite. You weren't passing the `storage` parameter required by SQLite though.

Let me know if this works, can be added! Not sure what other tests would be need to be added as well.

### CODE REVIEW

**Comment by lokenx** [comment]
The node 0.11 test is failing for some reason [here](https://travis-ci.org/danecando/hapi-sequelize/jobs/108355008#L194)

Completes [here](https://travis-ci.org/lokenx/hapi-sequelize) fine though :confused:

**Comment by lokenx** [comment]
`npm install` ([here](https://travis-ci.org/danecando/hapi-sequelize/jobs/108355008#L117)) seems to fail with 0.11 FYI.

**Comment by lokenx** [comment]
Any ideas regarding this PR/weird failing test?

**Comment by danecando** [comment]
no longer an issue with v3

**Pull request closed without merging**
